'use client'
import React from 'react'
import { Button } from '@/components/ui/button';
import { Download } from 'lucide-react';

const DownloadSummaryButton = ({title, summaryText, fileName, createdAt}:{title:string; summaryText:string; fileName:string; createdAt:string}) => {
    const handleDownload = ()=>{
        const summaryContent = `# ${title}

Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString()}
        
${summaryText}
        
Original File: ${fileName}
Generated by Summora
        `;
        const blob = new Blob([summaryContent], {type: 'text/plain'});
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `summary-${title.replace(/[^a-z0-9]/gi, '_')}.txt`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
    }
    
    return (
        <Button 
            size={'sm'} 
            className='h-9 px-4 bg-gradient-to-r from-rose-500 to-rose-600 text-white hover:from-rose-600 hover:to-rose-700 transition-all duration-300 shadow-md hover:shadow-lg rounded-lg group'
            onClick={handleDownload}
        >
            <Download className='h-4 w-4 mr-2 transition-transform group-hover:-translate-y-0.5' />
            Download Summary
        </Button>
    )
}

export default DownloadSummaryButton